# Generated by Django 6.0.5 on 2026-06-02 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='menuitem',
            options={'ordering': ['category', 'name']},
        ),
        migrations.RenameField(
            model_name='menuitem',
            old_name='available',
            new_name='is_available',
        ),
        migrations.AddField(
            model_name='menuitem',
            name='customizations',
            field=models.JSONField(blank=True, default=dict, help_text='e.g., {"spice_level": ["mild", "medium", "hot"]}'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='menu_items/'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='preparation_time',
            field=models.PositiveIntegerField(default=15, help_text='in minutes'),
        ),
    ]
