# Generated by Django 6.0.5 on 2026-06-02 06:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0001_initial'),
        ('orders', '0002_alter_order_options_alter_orderitem_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kitchenorderticket',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='kitchenorderticket',
            name='is_ready',
        ),
        migrations.AddField(
            model_name='kitchenorderticket',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kitchenorderticket',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='kitchenorderticket',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='kitchen_ticket', to='orders.order'),
        ),
    ]
